name: CI-CD
run-name: Running tests on ${{ github.actor }}'s commits

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Disable man-db
        uses: ./.github/composite/disable-mandb

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install -r --frozen-lockfile

      - name: Run Tests
        run: pnpm run test

  deploy-staging-cron:
    name: Deploy Cron to Staging
    needs: test
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load secrets
        uses: ./.github/composite/load-secrets
        with:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          UNLOAD_ENVIRONMENTS: ci,staging

      - name: Deploy Cron Service
        uses: ./.github/composite/deploy-cron
        with:
          DOCKER_HUB_PAT: ${{ env.DOCKER_HUB_PAT }}
          COOLIFY_PAT: ${{ env.COOLIFY_PAT }}
          COOLIFY_UUID: ${{ env.STAGING_COOLIFY_CRON_UUID }}
          TAG_PREFIX: staging-
          ENV_FILE: .env.staging

  deploy-staging-web:
    name: Deploy Web to Staging
    needs: test
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load secrets
        uses: ./.github/composite/load-secrets
        with:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          UNLOAD_ENVIRONMENTS: ci,staging

      - name: Deploy Web Service
        uses: ./.github/composite/deploy-web
        with:
          DOCKER_HUB_PAT: ${{ env.DOCKER_HUB_PAT }}
          COOLIFY_PAT: ${{ env.COOLIFY_PAT }}
          COOLIFY_UUID: ${{ env.STAGING_COOLIFY_WEB_UUID }}
          TAG_PREFIX: staging-
          ENV_FILE: .env.staging

  deploy-production-cron:
    name: Deploy Cron to Production
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load secrets
        uses: ./.github/composite/load-secrets
        with:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          UNLOAD_ENVIRONMENTS: ci,production

      - name: Deploy Cron Service
        uses: ./.github/composite/deploy-cron
        with:
          DOCKER_HUB_PAT: ${{ env.DOCKER_HUB_PAT }}
          COOLIFY_PAT: ${{ env.COOLIFY_PAT }}
          COOLIFY_UUID: ${{ env.PROD_COOLIFY_CRON_UUID }}
          TAG_PREFIX: ""
          ENV_FILE: .env.production

  deploy-production-web:
    name: Deploy Web to Production
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load secrets
        uses: ./.github/composite/load-secrets
        with:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          UNLOAD_ENVIRONMENTS: ci,production

      - name: Deploy Web Service
        uses: ./.github/composite/deploy-web
        with:
          DOCKER_HUB_PAT: ${{ env.DOCKER_HUB_PAT }}
          COOLIFY_PAT: ${{ env.COOLIFY_PAT }}
          COOLIFY_UUID: ${{ env.PROD_COOLIFY_WEB_UUID }}
          TAG_PREFIX: ""
          ENV_FILE: .env.production
